basic crud for user and ticket
JEub/dev-this-bug-tracker pull request #4
Opened 2023-07-28 04:49 UTC by d104601

2023-07-28 17:01 UTC, JEub requested changes
Please check all review comments. Also please add the .idea/ directory to your master git ignore file.

2023-07-28 17:01 UTC, JEub commented on backend/.idea/.gitignore
Please add the `.idea/` folder to the main `.gitignore` file and remove from all pushes.

2023-07-28 17:01 UTC, JEub commented on backend/main.py
> +from router import user, ticket
Generally here, I'd prefer you import the routers from each of these files. For instance...

```python
...
from router.user import router as user_router
from router.ticket import router as ticket_router
```

That being said, the way you have it below also makes sense. Just personal preferences. 

Good job.

2023-07-28 17:01 UTC, JEub commented on backend/main.py
> -@app.get("/")
We will add this back in. The root route should at the least return a list of available routes.

2023-07-28 17:01 UTC, JEub commented on backend/migrations/env.py
> +target_metadata = model.status.Base.metadata
I'm not convinced this is going to work for all of the metadata fields. Please be prepared to show us on Monday.

2023-07-28 17:01 UTC, JEub commented on backend/migrations/versions/55f4cf436441_.py
> +    # ### end Alembic commands ###
This looks good.

2023-07-28 17:01 UTC, JEub commented on backend/model/ticket.py
> +    description = Column(Text)
Does this work? I was not aware that sqlalchemy types now included a Text option. This is pretty cool.

2023-07-28 17:01 UTC, JEub commented on backend/router/ticket.py
> +@router.get("/")
I don't like that we have two routes with the same `/` endpoint. I'd like to avoid that. 

For the createTicket endpoint, let's make that `/create/` instead.

2023-07-28 17:01 UTC, JEub commented on backend/router/ticket.py
> +@router.put("/{id}")
We should make this `/update/{id}` instead.

2023-07-28 17:01 UTC, JEub commented on backend/router/ticket.py
> +        model = Ticket(title=ticket.title, description=ticket.description, start_date=ticket.start_date, completed_date=ticket.completed_date, status_id=ticket.status_id, story_points=ticket.story_po
This needs to be formatted. Please use the `black` package for formatting. 

From the root directory run:
```bash
black ./backend/
```

2023-07-28 17:01 UTC, JEub commented on backend/router/ticket.py
> +@router.delete("/{id}")
Update this route to be `/delete/{id}`

2023-07-28 17:01 UTC, JEub commented on backend/router/user.py
> +@router.post("/")
Make this route `/create/` instead of the root.

2023-07-28 17:01 UTC, JEub commented on backend/router/user.py
> +@router.put("/{id}")
Edit this to be `/update/{id}`.

2023-07-28 17:01 UTC, JEub commented on backend/router/user.py
> +def createUser(user: RequestBody):
Investigate the usage of `Depends` in the parameters instead of calling `with get_db()`.

2023-07-31 04:43 UTC, d104601 reviewed
I just applied all your feedbacks as much as I can. I will explain more detail at meeting on Monday.

2023-07-31 19:15 UTC, merged